name: C/C++ Build program

on:
  push:
    branches: [branchAutomake]
  pull_request:
    branches: [branchAutomake]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake g++

      - name: Generate configure script
        run: |
          autoreconf --install
        
      - name: Configure
        run: ./configure
      

      - name: Build program
        run: make

      - name: Create dist
        run: make dist

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
            name: dist
            path: '*.tar.gz'
