name: C/C++ Build program

on:
  push:
    branches: [branchHTTPserver]
  pull_request:
    branches: [branchHTTPserver]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake g++ libboost-test-dev

      - name: Regenerate configs
        run: |
          autoreconf --install
        
      - name: Configure
        run: ./configure
      
      - name: Build
        run: make

      - name: Run tests
        run: make check

      - name: QEMU install
        uses: docker/setup-qemu-action@v3

      - name: Install Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: build ls
        run: docker buildx ls

      - name: Login to docker hub
        run: docker login -u ${{ vars.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Dockerfile image arm64
        run: docker build --platform=linux/arm64 -t prokopchukm/optimaserver:arm64 --push .

      - name: Build Dockerfile image amd64
        run: docker build --platform=linux/amd64 -t prokopchukm/optimaserver:amd64 --push .

      - name: Docker manifest
        run: docker manifest create prokopchukm/optimaserver --amend prokopchukm/optimaserver:amd64 --amend prokopchukm/optimaserver:arm64

      - name: Push docker manifest 
        run: docker manifest push prokopchukm/optimaserver

