name: C/C++ Build program

on:
  push:
    branches: [branchAutoPackage]
  pull_request:
    branches: [branchAutoPackage]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake g++ debhelper devscripts
          sudo apt-get install build-essential

      - name: Generate configure script
        run: |
          autoreconf --install
        
      - name: Configure
        run: ./configure
      
      - name: Build
        run: make

      - name: Build package
        run: |
          dpkg-buildpackage -us -uc

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: func-class-deb
          path: /home/runner/work/TrigFunction/func-class_*.deb
