name: C/C++ Build program

on:
  push:
    branches: [branchAutoPackage]
  pull_request:
    branches: [branchAutoPackage]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake g++ debhelper devscripts

      - name: Generate configure script
        run: |
          autoreconf --install
        
      - name: Configure
        run: ./configure
      

       - name: Build Debian package
        run: |
          dpkg-buildpackage -us -uc

      - name: Build
        run: make

      - name: Upload Debian
        uses: actions/upload-artifact@v4
        with:
          name: FuncClass-deb
          path: /home/runner/work/Devops2/FuncClass_*.deb
