name: C/C++ Build program

on:
  push:
    branches: [branchAutoTest]
  pull_request:
    branches: [branchAutoTest]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake g++ libboost-test-dev

      - name: Generate configure script
        run: |
          autoreconf --install
        
      - name: Configure
        run: ./configure
      
      - name: Build
        run: make

      - name: Run tests
        run: make check
